import { CountryKey, CountryThemeConfig } from '../types/country';

export const THEME_CONFIGS: Record<CountryKey, CountryThemeConfig> = {
  colombia: {
    slug: 'colombia',
    name: 'Colombia',
    eyebrow: 'HOY INSPIRA A TODA LATINOAMÉRICA',
    title: 'Un propósito que nació de Colombia',
    desc: 'Una red que une personas, empresas y comunidades, para construir una región más humana, productiva y consciente.',
    themeColor: '#00AEEF',
    rgbColor: { r: 0, g: 174, b: 239 },
    gradient: 'from-brand-colombia/80 to-brand-bg/95',
  },
  ecuador: {
    slug: 'ecuador',
    name: 'Ecuador',
    eyebrow: 'CONECTANDO HISTORIAS DE CRECIMIENTO',
    title: 'Comunidades unidas por el desarrollo',
    desc: 'Impulsamos el desarrollo local en Ecuador mediante alianzas estratégicas que potencian el talento y las oportunidades productivas.',
    themeColor: '#FF7A50',
    rgbColor: { r: 255, g: 122, b: 80 },
    gradient: 'from-brand-ecuador/80 to-brand-bg/95',
  },
  chile: {
    slug: 'chile',
    name: 'Chile',
    eyebrow: 'TEJIENDO REDES DE SOLIDARIDAD SOCIAL',
    title: 'Impacto que cruza las fronteras',
    desc: 'Fortalecemos la cohesión social en Chile creando lazos de apoyo mutuo que permiten escalar soluciones innovadoras y sostenibles.',
    themeColor: '#E72B5A',
    rgbColor: { r: 231, g: 43, b: 90 },
    gradient: 'from-brand-chile/80 to-brand-bg/95',
  },
  argentina: {
    slug: 'argentina',
    name: 'Argentina',
    eyebrow: 'CONSTRUYENDO EL FUTURO DESDE CADA PROVINCIA',
    title: 'Una red en pleno crecimiento',
    desc: 'Promovemos el empleo y el emprendimiento en Argentina con un enfoque federal, conectando recursos y voluntades locales.',
    themeColor: '#7A0A83',
    rgbColor: { r: 122, g: 10, b: 131 },
    gradient: 'from-brand-argentina/80 to-brand-bg/95',
  },
  latam: {
    slug: 'latam',
    name: 'Latinoamérica',
    eyebrow: 'HOY INSPIRA A TODA LATINOAMÉRICA',
    title: 'Un propósito que nació de Colombia',
    desc: 'Una red que une personas, empresas y comunidades, para construir una región más humana, productiva y consciente.',
    themeColor: '#4B075C',
    rgbColor: { r: 75, g: 7, b: 92 },
    gradient: 'from-brand-latam/80 to-brand-bg/95',
  },
};
